VERSION=VERSION_STRING_PLACEHOLDER

default:
	@curl -O http://builds.emberjs.com/tags/$(VERSION)/ember-data.js
	@curl -O http://builds.emberjs.com/tags/$(VERSION)/ember-data.min.js
	@curl -O http://builds.emberjs.com/tags/$(VERSION)/ember-data.prod.js

.PHONY: default
