# Save as .codeclimate.yml (note leading .) in project root directory
languages:
  JavaScript: true

exclude_paths:
  - "tests/*"
  - "generators/*"
  - "blueprints/*"
  - "bin/*"
  - "lib/*"
  - "node-tests/*"

version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    enabled: false # we should re-enable this and slowly reduce to ~750 over time
  method-complexity:
    enabled: false # we should re-enable this and slowly reduce to ~10 over time
  method-count:
    config:
      threshold: 50
  method-lines:
    config:
      threshold: 100
  identical-code:
    enabled: false # we should re-enable this once we no longer have a separate build step for RecordData
