parameters:
  nodeVersion: '10.x'

steps:
  - script: brew update && brew cask install google-chrome
    displayName: 'Install Google Chrome'
    condition: eq(variables['Agent.OS'], 'Darwin')

  - task: NodeTool@0
    displayName: 'Install Node'
    inputs:
      versionSpec: ${{ parameters.nodeVersion }}
