export type {
  Meta,
  LinkObject,
  Link,
  Links,
  PaginationLinks,
  ExistingResourceIdentifierObject,
  NewResourceIdentifierObject,
  ResourceIdentifier,
  ResourceIdentifierObject,
  SingleResourceRelationship,
  CollectionResourceRelationship,
  InnerRelationshipDocument,
  ResourceRelationshipsObject,
  ResourceObject,
  NewResourceObject,
  ExistingResourceObject,
  EmptyResourceDocument,
  SingleResourceDocument,
  CollectionResourceDocument,
  JsonApiDocument,
} from '@warp-drive/core-types/spec/json-api-raw';
