export function gte(library: string, version: string): boolean;
export function gte(version: string): boolean;
export function lte(library: string, version: string): boolean;
export function lte(version: string): boolean;
export const HAS_UNDERSCORE_ACTIONS: boolean;
export const HAS_MODERN_FACTORY_INJECTIONS: boolean;
export const HAS_DESCRIPTOR_TRAP: boolean;
export const HAS_NATIVE_COMPUTED_GETTERS: boolean;
export const IS_GLIMMER_2: boolean;
export const IS_RECORD_DATA: boolean;
export const SUPPORTS_FACTORY_FOR: boolean;
export const SUPPORTS_GET_OWNER: boolean;
export const SUPPORTS_SET_OWNER: boolean;
export const SUPPORTS_NEW_COMPUTED: boolean;
export const SUPPORTS_INVERSE_BLOCK: boolean;
export const SUPPORTS_CLOSURE_ACTIONS: boolean;
export const SUPPORTS_UNIQ_BY_COMPUTED: boolean;
