export const LOG_PAYLOADS: boolean;
export const LOG_OPERATIONS: boolean;
export const LOG_MUTATIONS: boolean;
export const LOG_NOTIFICATIONS: boolean;
export const LOG_REQUESTS: boolean;
export const LOG_REQUEST_STATUS: boolean;
export const LOG_IDENTIFIERS: boolean;
export const LOG_GRAPH: boolean;
export const LOG_INSTANCE_CACHE: boolean;
