name: Canary-Mirror-Beta Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Run publish script
    runs-on: ubuntu-latest
    environment: deployment
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          fetch-depth: 3
          ref: beta
      - run: git fetch origin main --depth=1
      - name: Get last beta version from package.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: 'jq .version package.json -r'
      - name: Reset the Beta Branch
        run: git reset --hard origin/main && git push origin beta -f
      - uses: ./.github/actions/setup
        with:
          build-addons: true
          install: true
      - name: Make sure git user is setup
        run: |
          git config --local user.email 'tomster@emberjs.com'
          git config --local user.name 'Ember.js Alpha Releaser'
      - name: Publish with script
        run: node scripts/publish.js beta --skipSmokeTest --fromVersion=${{ steps.version.outputs.value }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - name: Push branch + tag
        run: git push origin HEAD --follow-tags
      - uses: actions/upload-artifact@v3
        with:
          name: tarballs
          path: ember-data-*.tgz
