name: Canary-Mirror-Beta Release

on:
  workflow_dispatch:

env:
  TURBO_API: http://127.0.0.1:9080
  TURBO_TOKEN: this-is-not-a-secret
  TURBO_TEAM: myself

jobs:
  release:
    name: Run publish script
    runs-on: ubuntu-latest
    environment: deployment
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 3
          ref: beta
      - run: git fetch origin main --depth=1
      - name: Get last beta version from package.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: 'jq .version package.json -r'
      - name: Reset the Beta Branch
        run: git reset --hard origin/main && git push origin beta -f
      - uses: ./.github/actions/setup
        with:
          build-addons: true
          install: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Make sure git user is setup
        run: |
          git config --local user.email 'tomster@emberjs.com'
          git config --local user.name 'Ember.js Alpha Releaser'
      - name: Publish with script
        run: node scripts/publish.js beta --skipSmokeTest --fromVersion=${{ steps.version.outputs.value }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - name: Push branch + tag
        run: git push origin HEAD --follow-tags
      - uses: actions/upload-artifact@v4
        with:
          name: tarballs
          path: ember-data-*.tgz
