name: DX

on:
  pull_request:
    branches:
      - main
      - v4-main

env:
  TURBO_API: http://127.0.0.1:9080
  TURBO_TOKEN: this-is-not-a-secret
  TURBO_TEAM: myself

concurrency:
  group: docs-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: ./.github/actions/setup
        with:
          install: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      # Deactivated while we restructure the docs to use tsdoc and typedoc,
      # since this is based on the yuidocs parser output.
      # - name: Test Docs
      #   run: pnpm test:docs
      - name: Test Blueprints
        run: pnpm test:blueprints
