name: DX

on:
  pull_request:
    branches:
      - main

env:
  TURBO_API: http://127.0.0.1:9080
  TURBO_TOKEN: this-is-not-a-secret
  TURBO_TEAM: myself

concurrency:
  group: docs-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: ./.github/actions/setup
        with:
          install: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Test Docs
        run: pnpm test:docs
      - name: Test Blueprints
        run: pnpm test:blueprints
