name: Contract

on:
  pull_request:
    branches:
      - main

concurrency:
  group: encapsulation-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - uses: ./.github/actions/setup
        with:
          restore-broccoli-cache: true
          install: true
      - name: Run Tests
        run: pnpm test:encapsulation
