name: Enforce Release PR labeling

on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, edited, synchronize]
    branches:
      - release

concurrency:
  group: pr-labels-release-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  enforce-changelog-label:
    runs-on: ubuntu-latest
    steps:
      - uses: yogevbd/enforce-label-action@2.2.2
        with:
          REQUIRED_LABELS_ANY: 'changelog:breaking,changelog:feat,changelog:bugfix,changelog:perf,changelog:cleanup,changelog:deprecation,changelog:doc,changelog:test,changelog:chore,skip-changelog'
          REQUIRED_LABELS_ANY_DESCRIPTION: "Select at least one label for changelog generation. Use the label `skip-changelog` and none of the others in the list to avoid this being included. ['changelog:breaking', 'changelog:feat', 'changelog:bugfix', 'changelog:perf', 'changelog:cleanup', 'changelog:deprecation', 'changelog:doc', 'changelog:test', 'changelog:chore', 'skip-changelog']"
  ban-target-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: yogevbd/enforce-label-action@2.2.2
        with:
          BANNED_LABELS: 'target:canary,target:beta,target:release,target:lts,target:lts-prev'
          BANNED_LABELS_DESCRIPTION: "These labels should only be used for PRs targeting the master branch, remove them. ['target:canary', 'target:beta', 'target:release', 'target:lts', 'target:lts-prev']"
  ban-other-release-branch-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: yogevbd/enforce-label-action@2.2.2
        with:
          BANNED_LABELS: 'backport-beta,backport-lts,backport-lts-prev,backport-old-release'
          BANNED_LABELS_DESCRIPTION: "The following labels should only be applied to PRs targeting other release channel branches, remove them.['backport-beta', 'backport-lts', 'backport-lts-prev', 'backport-old-release']"
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1.1.3
        with:
          labels: backport-release
