name: Infra Tests

on:
  pull_request:
    branches:
      - master
    types:
      - labeled
      - synchronize
      - ready_for_review

concurrency:
  group: infra-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    if: contains(github.event.pull_request.labels.*.name, 'ci-compat-infra')
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
        with:
          restore-broccoli-cache: true
          build-addons: true
          install: true
      - name: pnpm test infra compatWith 3.0
        env:
          COMPAT_WITH: '3.0'
        run: pnpm test:infra
      - name: pnpm test infra compatWith 3.8
        env:
          COMPAT_WITH: '3.8'
        run: pnpm test:infra
      - name: pnpm test infra compatWith 3.12
        env:
          COMPAT_WITH: '3.12'
        run: pnpm test:infra
      - name: pnpm test infra compatWith 3.16
        env:
          COMPAT_WITH: '3.16'
        run: pnpm test:infra
      - name: pnpm test infra compatWith 99.0
        env:
          COMPAT_WITH: '99.0'
        run: pnpm test:infra
