name: Infra

on:
  pull_request:
    branches:
      - main
    types:
      - labeled
      - synchronize
      - ready_for_review

env:
  TURBO_API: http://127.0.0.1:9080
  TURBO_TOKEN: this-is-not-a-secret
  TURBO_TEAM: myself

concurrency:
  group: infra-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    if: contains(github.event.pull_request.labels.*.name, 'ci-compat-infra')
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: ./.github/actions/setup
        with:
          restore-broccoli-cache: true
          install: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: pnpm test infra compatWith 3.0
        env:
          COMPAT_WITH: '3.0'
        run: pnpm test:infra
      - name: pnpm test infra compatWith 3.8
        env:
          COMPAT_WITH: '3.8'
        run: pnpm test:infra
      - name: pnpm test infra compatWith 3.12
        env:
          COMPAT_WITH: '3.12'
        run: pnpm test:infra
      - name: pnpm test infra compatWith 3.16
        env:
          COMPAT_WITH: '3.16'
        run: pnpm test:infra
      - name: pnpm test infra compatWith 99.0
        env:
          COMPAT_WITH: '99.0'
        run: pnpm test:infra
